//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public System.DateTime Дата { get; set; }
        public int НомерЗаказа { get; set; }
        public Nullable<int> Клиент { get; set; }
        public string МаркаАвтомобиля { get; set; }
        public Nullable<int> КодРаботы { get; set; }
        public Nullable<int> КодИсполнителя { get; set; }
    
        public virtual ВидыРаботы ВидыРаботы { get; set; }
        public virtual Исполнители Исполнители { get; set; }
        public virtual Клиенты Клиенты { get; set; }
    }
}
